on:
  pull_request:
    branches:
      -  main


jobs:
  compare-dependencies:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3,12', '3.13']
        
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4 # checkout multiple repos

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipreqs
        run: pip install pipreqs

      - name: Run pipreqs on PR branch
        run: |
          pipreqs . --force
          cp requirements.txt pr-requirements.txt

      - name: Checkout main branch
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }}

      - name: Run pip reqs on main branch
        run: |
          pip install pipreqs
          pipreqs . --force
          cp requirements.txt base-requirements.txt

      - name: Compare requirements between PR branch and main branch
        run: |
          echo "New pip packages added in PR:"
          comm -13 <(sort base-requirements.txt) <(sort pr-requirements.txt) || true
          echo "Packages removed in PR:"
          comm -23 <(sort base-requirements.txt) <(sort pr-requirements.txt) || true


